name: Running Unit Test

on:
  pull_request:
    branches:
      - 'master'
      - 'main'
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  unit-test:
    name: "unit test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: running unit test
        run: go test ./... -cover

  build-push-docker:
    name: "Build image & push registry to dockerhub"
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - name: copy value config.json
        env:
          CONFIG_JSON: ${{secrets.CONFIG_JSON}}
        run: echo "$CONFIG_JSON" > config.json
      - name: build docker
        run: docker build -t raffiarmydar/mikro:1.0.0 .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push image to registry docker hub
        run: docker push raffiarmydar/mikro:1.0.0

  deploy-to-ec2:
    name: "Deploy to ec2 from registry docker hub"
    runs-on: ubuntu-latest
    needs: build-push-docker
    steps:
      - uses: actions/checkout@v2
      - name: configuration SSH
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/publickey.pem
          chmod 400 ~/.ssh/publickey.pem
          cat >>~/.ssh/config <<END
          Host development
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/publickey.pem
            StrictHostKeyChecking=no
          END
      - name: Connect EC2 & Remove All Container & Pull from Registry & Start
        run: ssh development 'docker rm -f $(docker ps -a -q) && docker pull raffiarmydar/mikro:1.0.0 && docker run -d -p 8080:8080 --name mikro raffiarmydar/mikro:1.0.0'
